name: Build & attach release assets for Linux

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-linux:
    name: Linux release asset
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Assemble app
        run: |
          ./gradlew assemble

      - name: Download JavaFX
        run: |
          chmod +x release-linux/download-jfx.sh
          cd release-linux/
          ./download-jfx.sh

      - name: Run Linux release script
        run: |
          chmod +x release-linux/make-release.sh
          cd release-linux/
          ./make-release.sh "$(pwd)/jfx-linux/" $JAVA_HOME

      - name: Upload Linux asset to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: generated/Vocabulary-Helepr-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}